services:
  app:
    image: ${APP_IMAGE:-ghcr.io/tuandm21/flight_be:main-20250925}
    container_name: flight-app-prod
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "curl -f http://localhost:$$SERVER_PORT/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    networks:
      - be_airport-network
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped

  migration:
    build:
      context: .
      dockerfile: Dockerfile.migration
    container_name: flight-migration-prod
    working_dir: /flyway
    env_file:
      - .env
    environment:
      - FLYWAY_URL=jdbc:mariadb://mariadb:${MYSQL_PORT}/${MYSQL_DATABASE}
      - FLYWAY_USER=${FLYWAY_USER}
      - FLYWAY_PASSWORD=${FLYWAY_PASSWORD}
      - FLYWAY_BASELINE_ON_MIGRATE=true
      - FLYWAY_CLEAN_DISABLED=false
    networks:
      - be_airport-network
    depends_on:
      mariadb:
        condition: service_healthy
    profiles:
      - migration

  mariadb:
    build:
      context: .
      dockerfile: Dockerfile.mariadb
    container_name: flight-mariadb-prod
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mariadb_data_prod:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${SPRING_DATASOURCE_USERNAME}
      - MYSQL_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_allowed_packet=256M --skip-log-bin --skip-log-slave-updates --innodb_flush_log_at_trx_commit=0
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "mariadb -uroot -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1' || exit 1",
        ]
      start_period: 60s
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      - be_airport-network
    restart: unless-stopped

volumes:
  mariadb_data_prod:
    name: flight-mariadb-data-prod

networks:
  be_airport-network:
    name: be_airport-network
    driver: bridge
