services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: flight-app-dev
    ports:
      - "8080:8080"
      - "35729:35729"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
    volumes:
      - ./src:/app/src
      - ./target:/app/target
      - ~/.m2:/root/.m2
    networks:
      - airport-network
    depends_on:
      - mariadb

  migration:
    image: maven:3.9-eclipse-temurin-17
    container_name: flight-migration-dev
    working_dir: /app
    volumes:
      - .:/app
      - maven_cache_dev:/root/.m2
    env_file:
      - .env
    networks:
      - airport-network
    depends_on:
      - mariadb
    profiles:
      - migration

  mariadb:
    image: mariadb:11.4
    container_name: flight-mariadb-dev
    env_file:
      - .env
    environment:
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data_dev:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_allowed_packet=256M
    networks:
      - airport-network

volumes:
  mariadb_data_dev:
  maven_cache_dev:

networks:
  airport-network:
    driver: bridge
