services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flight-app-prod
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - airport-network
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped

  migration:
    image: maven:3.9-eclipse-temurin-17
    container_name: flight-migration-prod
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${SPRING_DATASOURCE_USERNAME}"
      MYSQL_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
    networks:
      - airport-network
    depends_on:
      mariadb:
        condition: service_healthy
    profiles:
      - migration

  mariadb:
    image: mariadb:11.4
    container_name: flight-mariadb-prod
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data_prod:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_allowed_packet=256M
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - airport-network
    restart: unless-stopped

volumes:
  mariadb_data_prod:

networks:
  airport-network:
    driver: bridge
